version: '3'
services:
  jekyll:
    image: "jekyll/jekyll:3.8.5"
    restart: always
    ports:
      - "4000:4000"
    volumes:
      - .:/srv/jekyll
      - ./bundle:/usr/local/bundle
    command: jekyll serve
